### ISSUE TITLE
How to run the core

### ISSUE THREAD

**Issue by palmerj** [Rinnegatamante/dhewm3-libretro#2]
How do you run the core with retroarch? I've compiled the source using the makefile (actually using the fork https://github.com/libretro/boom3), but I can't get the core to work. I've got all the game files in /retro/roms/ports/doom3/base

```
/opt/retro/emulators/retroarch/bin/retroarch --verbose -L /opt/retro/libretrocores/lr-boom3/boom3_libretro.so ~/retro/roms/ports/doom3/base/pak000.pk4 
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirecting save file to "/home/retro/roms/ports/doom3/base/pak000.srm".
[INFO] Redirecting save state to "/home/retro/roms/ports/doom3/base/pak000.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Dec 24 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retro/libretrocores/lr-boom3/boom3_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /home/retro/.config/retroarch/config/boom3/boom3.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /home/retro/.config/retroarch/config/boom3/base.cfg.
[INFO] [Overrides] no game-specific overrides found at /home/retro/.config/retroarch/config/boom3/pak000.cfg.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /home/retro/.config/retroarch/config/remaps
[INFO] Redirecting save file to "/home/retro/roms/ports/doom3/base/pak000.srm".
[INFO] Redirecting save state to "/home/retro/roms/ports/doom3/base/pak000.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[libretro INFO] Got size: 960 x 544.
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/retro/.config/retroarch/cheats/boom3/pak000.cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ 2880x1632
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [GLX]: X = 0, Y = 0, W = 2880, H = 1632.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2).
[INFO] [GL]: Version: 3.0 Mesa 20.0.8.
[INFO] [GL]: Using resolution 1920x966
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures./opt/retro/emulators/retroarch/bin/retroarch --verbose -L /opt/retro/libretrocores/lr-boom3/boom3_libretro.so ~/retro/roms/ports/doom3/base/pak000.pk4 
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirecting save file to "/home/retro/roms/ports/doom3/base/pak000.srm".
[INFO] Redirecting save state to "/home/retro/roms/ports/doom3/base/pak000.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Dec 24 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retro/libretrocores/lr-boom3/boom3_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /home/retro/.config/retroarch/config/boom3/boom3.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /home/retro/.config/retroarch/config/boom3/base.cfg.
[INFO] [Overrides] no game-specific overrides found at /home/retro/.config/retroarch/config/boom3/pak000.cfg.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /home/retro/.config/retroarch/config/remaps
[INFO] Redirecting save file to "/home/retro/roms/ports/doom3/base/pak000.srm".
[INFO] Redirecting save state to "/home/retro/roms/ports/doom3/base/pak000.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[libretro INFO] Got size: 960 x 544.
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/retro/.config/retroarch/cheats/boom3/pak000.cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ 2880x1632
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [GLX]: X = 0, Y = 0, W = 2880, H = 1632.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2).
[INFO] [GL]: Version: 3.0 Mesa 20.0.8.
[INFO] [GL]: Using resolution 1920x966
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  71
  Current serial number in output stream:  71
```

**Comment by palmerj** [comment]
Can anyone please help?

**Comment by Rinnegatamante** [comment]
This looks like a driver issue more than a core issue.

**Comment by palmerj** [comment]
Thanks for the reply. Sorry I originally missed this!

Note I'm able to get `dhewm3` working on on the same machine, so I started to think this is related to something in this core or libretro/retroarch. In the end I upgraded to retroarch master and I managed to get the core to launch the game. The big issue now is:

1. I can't get make gamepad to do anything on the menu (it's 6 button only with a dpad https://www.8bitdo.com/m30-2-4g/). Any ideas?
2. When I exit retroarch the software coredumps leaving my screen resolution at the fullscreen resolution I set for retroarch. Here's the backtrace. I could build it with symbols if that helps more.

```
Starting program: /opt/retropie/emulators/retroarch/bin/retroarch --verbose -L /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so --config /opt/retropie/configs/all/retroarch/config/boom3/boom3.cfg /home/pi/RetroPie/roms/ports/doom3/base/pak000.pk4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[INFO] RetroArch 1.9.0 (Git b83d049)
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/ports/doom3/base/pak000.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/ports/doom3/base/pak000.state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Jan 30 2021
[INFO] Version: 1.9.0
[INFO] Git: b83d049
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [CORE]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-boom3/boom3_libretro.so"
[INFO] [Overrides]: Core-specific overrides found at /home/pi/.config/retroarch/config/boom3/boom3.cfg.
[INFO] [Overrides]: No content-dir-specific overrides found at /home/pi/.config/retroarch/config/boom3/base.cfg.
[INFO] [Overrides]: No game-specific overrides found at /home/pi/.config/retroarch/config/boom3/pak000.cfg.
[INFO] Config: appending config "/home/pi/.config/retroarch/config/boom3/boom3.cfg"
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /home/pi/.config/retroarch/config/remaps
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/ports/doom3/base/pak000.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/ports/doom3/base/pak000.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_HW_RENDER, context type: gl.
[INFO] Requesting OpenGL context.
[INFO] Reached end of SET_HW_RENDER.
[INFO] [Environ]: SET_HW_SHARED_CONTEXT.
[libretro INFO] Got size: 1280 x 720.
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [SRAM]: Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/pi/.config/retroarch/cheats/boom3/pak000.cht
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ 3840x2160
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[New Thread 0x7fffe734e700 (LWP 212237)]
[New Thread 0x7fffe6b4d700 (LWP 212238)]
[New Thread 0x7fffe634c700 (LWP 212239)]
[New Thread 0x7fffe5b4b700 (LWP 212240)]
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2160.
[INFO] [GLX]: Creating shared HW context.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2).
[INFO] [GL]: Version: 3.0 Mesa 21.1.0-devel (git-205e737 2021-01-30 focal-oibaf-ppa).
[INFO] [GL]: Using resolution 1920x966
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (2048 x 2048).
[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [udev]: Pad #0 (/dev/input/event3) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [DBus]: Suspended screensaver via DBus.
[INFO] [Video]: Found display server: x11
[New Thread 0x7fffd4cf8700 (LWP 212242)]
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 22272.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Display]: Found display driver: "gl".
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] Disconnecting device from port 6.
[INFO] Disconnecting device from port 7.
[INFO] Disconnecting device from port 8.
[INFO] Disconnecting device from port 9.
[INFO] Disconnecting device from port 10.
[INFO] Disconnecting device from port 11.
[INFO] Disconnecting device from port 12.
[INFO] Disconnecting device from port 13.
[INFO] Disconnecting device from port 14.
[INFO] Disconnecting device from port 15.
[INFO] Disconnecting device from port 16.
[INFO] [Playlist]: Loading history file: [/opt/retropie/configs/all/retroarch/config/boom3/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/opt/retropie/configs/all/retroarch/config/boom3/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/opt/retropie/configs/all/retroarch/config/boom3/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/opt/retropie/configs/all/retroarch/config/boom3/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/opt/retropie/configs/all/retroarch/config/boom3/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapInterval(1)
pid: 212236
1024 MB System Memory
Sys_InitNetworking: adding loopback interface
----- Initializing File System -----
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/pi/RetroPie/roms/ports/doom3/base/pak008.pk4 with checksum 0x23ae5993
Current search path:
/home/pi/RetroPie/roms/ports/doom3/base
/home/pi/RetroPie/roms/ports/doom3/base/pak008.pk4 (3 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak007.pk4 (38 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak006.pk4 (48 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak005.pk4 (63 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak004.pk4 (5137 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak003.pk4 (4676 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak002.pk4 (6120 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak001.pk4 (8972 files)
/home/pi/RetroPie/roms/ports/doom3/base/pak000.pk4 (2698 files)
Addon pk4s:
[New Thread 0x7fffbae35700 (LWP 212243)]
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing libretro.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing Sound System -----
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
Initializing sound system
Initializing non OpenAL sound system...
Non OpenAL sound system initialized...
OpenGL vendor: Intel Open Source Technology Center
OpenGL renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL version: 3.0 Mesa 21.1.0-devel (git-205e737 2021-01-30 focal-oibaf-ppa)
...using GL_ARB_multitexture
...using GL_ARB_texture_env_combine
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_env_dot3
...using GL_ARB_texture_env_add
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_compression
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
X..GL_EXT_shared_texture_palette not found
...using GL_EXT_texture3D
...using GL_EXT_stencil_wrap
...using GL_EXT_stencil_two_side
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
...using GL_ARB_fragment_program
X..EXT_depth_bounds_test not found
ARB2 renderer: Available.
----- R_ReloadARBPrograms -----
glprogs/test.vfp
glprogs/test.vfp
glprogs/interaction.vfp
glprogs/interaction.vfp
glprogs/bumpyEnvironment.vfp
glprogs/bumpyEnvironment.vfp
glprogs/ambientLight.vfp
glprogs/ambientLight.vfp
glprogs/shadow.vp
glprogs/environment.vfp
glprogs/environment.vfp
glprogs/arbVP_glasswarp.txt: File not found
glprogs/arbFP_glasswarp.txt: File not found
using ARB_vertex_buffer_object memory
using ARB2 renderSystem
----- Initializing Game -----
gamename: baseDOOM-1
gamedate: Dec 29 2020
Initializing event system
...473 event definitions
Initializing class hierarchy
...142 classes, 764368 bytes for event callbacks
Initializing scripts
Compiled 'removeInitialSplineAngles': 720 ms
----- Compile stats -----
Memory usage:
     Strings: 79, 13232 bytes
  Statements: 67875, 2715000 bytes
   Functions: 2109, 318020 bytes
   Variables: 170888 bytes
    Mem used: 4483712 bytes
 Static data: 4214344 bytes
   Allocated: 5768260 bytes
 Thread size: 14056 bytes
...6 aas types
----- Initializing Session -----
[New Thread 0x7fffb8130700 (LWP 212244)]
[INFO] [Overrides]: Configuration overrides unloaded, original configuration restored.
[INFO] [config] Saved new config to "/opt/retropie/configs/all/retroarch/config/boom3/boom3.cfg".
[INFO] [Cheats]: Save game-specific cheatfile: /home/pi/.config/retroarch/cheats/boom3/pak000.cht
[INFO] Content ran for a total of: 00 hours, 00 minutes, 17 seconds.
[INFO] [CORE]: Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] [CORE]: Unloading core..
[INFO] [CORE]: Unloading core symbols..

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007fffe8bf17be in idBTree<idDynamicBlock<char>, int, 4>::Remove(idBTreeNode<idDynamicBlock<char>, int>*) ()
   from /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
(gdb) bt
#0  0x00007fffe8bf17be in idBTree<idDynamicBlock<char>, int, 4>::Remove(idBTreeNode<idDynamicBlock<char>, int>*)
    () at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#1  0x00007fffe8bf1d6e in idDynamicBlockAlloc<char, 262144, 128>::FreeInternal(idDynamicBlock<char>*) ()
    at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#2  0x00007fffe8bef1a4 in idStr::FreeData() () at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#3  0x00007fffe8a06fc4 in idFileSystemLocal::~idFileSystemLocal() ()
    at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#4  0x00007ffff40ae15e in __cxa_finalize (d=0x7fffe8fbb640) at cxa_finalize.c:83
#5  0x00007fffe886cbc7 in __do_global_dtors_aux () at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#6  0x00007fffe8f7e918 in __do_global_dtors_aux_fini_array_entry ()
    at /opt/retropie/libretrocores/lr-boom3/boom3_libretro.so
#7  0x00007ffff7fe5942 in  () at /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff41c7915 in __GI__dl_catch_exception
    (exception=<optimised out>, operate=<optimised out>, args=<optimised out>) at dl-error-skeleton.c:182
#9  0x00007ffff7fe5f26 in  () at /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff7fe6ef5 in  () at /lib64/ld-linux-x86-64.so.2
#11 0x00007ffff41c78b8 in __GI__dl_catch_exception
    (exception=exception@entry=0x7fffffff4bc0, operate=<optimised out>, args=<optimised out>)
    at dl-error-skeleton.c:208
#12 0x00007ffff41c7983 in __GI__dl_catch_error
    (objname=0x5555561ad320, errstring=0x5555561ad328, mallocedp=0x5555561ad318, operate=<optimised out>, args=<optimised out>) at dl-error-skeleton.c:227
#13 0x00007ffff45a2b59 in _dlerror_run (operate=operate@entry=0x7ffff45a2420 <dlclose_doit>, args=0x5555561b3f20)
    at dlerror.c:170
#14 0x00007ffff45a2468 in __dlclose (handle=<optimised out>) at dlclose.c:46
#15 0x0000555555607f97 in command_event ()
#16 0x00005555556103b5 in rarch_ctl ()
#17 0x0000555555612e58 in main_exit ()
#18 0x0000555555622439 in rarch_main ()
#19 0x00007ffff408b0b3 in __libc_start_main (main=
    0x5555555e3ee0 <main>, argc=7, argv=0x7fffffffdfb8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffdfa8) at ../csu/libc-start.c:308
#20 0x00005555555e421e in _start ()
```
Here are my machine details if that helps: https://gist.github.com/palmerj/0ddc07bd64970fe1402eccf913a0b5f8
